In [3]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

DEPRECATION: Loading egg at e:\anaconda\envs\text_analytics\lib\site-packages\huggingface_hub-0.28.1-py3.8.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

In [11]:
#lookup table mapping 
import pandas as pd

lookup_df = pd.read_csv("D:\VIS coursework\Lookup_table.csv")

lookup_df = lookup_df.rename(columns={
    'LAD11CD': 'Old_Code',
    'LAD21CD': 'New_Code'
})

def map_area_codes(df):
    if 'Area Code' in df.columns:
        df = df.merge(lookup_df[['Old_Code', 'New_Code']], how='left', left_on='Area Code', right_on='Old_Code')
        df['Area Code'] = df['New_Code'].combine_first(df['Area Code'])  # use 2021 code if available
        df.drop(columns=['Old_Code', 'New_Code'], inplace=True)
    return df

In [9]:
print(lookup_df.columns)

Index(['LAD11CD', 'LAD11NM', 'LAD11NMW', 'LAD21CD', 'LAD21NM', 'LAD21NMW',
       'ObjectId'],
      dtype='object')

In [14]:
import pandas as pd
import numpy as np

file_2011 = "D:\\VIS coursework\\excel datasets 2011 VISCOU\\economic acitivity_ 2011.xlsx"
file_2021 = "D:\VIS coursework\excel datasets 2021 VISCOU\economic_activity_status_2021.xlsx"

df_2011 = pd.read_excel(file_2011, skiprows=7).iloc[:-59]
df_2021 = pd.read_excel(file_2021, skiprows=7).iloc[:-2]

df_2011.tail()

c:\users\satheesh\appdata\local\programs\python\python39\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\users\satheesh\appdata\local\programs\python\python39\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,local authority: district / unitary (prior to April 2015),Unnamed: 1,All usual residents aged 16 to 74,Economically active: In employment,Economically active: Employee: Part-time,Economically active: Employee: Full-time,Economically active: Unemployed,Economically active: Full-time student,Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Other
344,Blaenau Gwent,W06000019,51809.0,27516.0,6763.0,18147.0,3557.0,1072.0,8709.0,2245.0,1403.0
345,Torfaen,W06000020,66107.0,38965.0,9535.0,25574.0,3163.0,1692.0,11115.0,2662.0,1203.0
346,Monmouthshire,W06000021,66107.0,41554.0,9352.0,24246.0,2217.0,1501.0,11640.0,2838.0,1285.0
347,Newport,W06000022,105141.0,61602.0,15531.0,39177.0,5616.0,3793.0,15389.0,5591.0,2469.0
348,Aberdeen City,S12000033,174869.0,109950.0,20380.0,79453.0,5367.0,12789.0,18757.0,13512.0,2875.0

In [2]:
df_2021.head

<bound method NDFrame.head of     local authority: district / unitary (as of April 2023) Unnamed: 1  \
0                                           Hartlepool      E06000001
1                                        Middlesbrough      E06000002
2                                 Redcar and Cleveland      E06000003
3                                     Stockton-on-Tees      E06000004
4                                           Darlington      E06000005
..                                                 ...            ...
313                                            Torfaen      W06000020
314                                      Monmouthshire      W06000021
315                                            Newport      W06000022
316                                              Powys      W06000023
317                                     Merthyr Tydfil      W06000024

     Economically active (excluding full-time students):In employment  \
0                                              36846.0
1                                              53849.0
2                                              54282.0
3                                              84174.0
4                                              48103.0
..                                                 ...
313                                            39763.0
314                                            42025.0
315                                            70863.0
316                                            60699.0
317                                            25035.0

     Economically active (excluding full-time students):In employment:Employee  \
0                                              32298.0
1                                              47228.0
2                                              47224.0
3                                              73699.0
4                                              42072.0
..                                                 ...
313                                            35275.0
314                                            33718.0
315                                            62494.0
316                                            43856.0
317                                            22007.0

     Economically active (excluding full-time students): In employment: Employee: Part-time  \
0                                               9575.0
1                                              14198.0
2                                              14167.0
3                                              19945.0
4                                              10748.0
..                                                 ...
313                                             8918.0
314                                             9140.0
315                                            15978.0
316                                            13628.0
317                                             5761.0

     Economically active (excluding full-time students): In employment: Employee: Full-time  \
0                                              22723.0
1                                              33030.0
2                                              33057.0
3                                              53754.0
4                                              31324.0
..                                                 ...
313                                            26357.0
314                                            24578.0
315                                            46516.0
316                                            30228.0
317                                            16246.0

     Economically active (excluding full-time students):In employment:Self-employed with employees  \
0                                                872.0
1                                               1245.0
2                                               1294.0
3                                               1994.0
4                                               1150.0
..                                                 ...
313                                              775.0
314                                             1463.0
315                                             1528.0
316                                             2614.0
317                                              623.0

     Economically active (excluding full-time students): In employment: Self-employed with employees: Part-time  \
0                                                210.0
1                                                376.0
2                                                313.0
3                                                462.0
4                                                258.0
..                                                 ...
313                                              143.0
314                                              321.0
315                                              377.0
316                                              497.0
317                                              127.0

     Economically active (excluding full-time students): In employment: Self-employed with employees: Full-time  \
0                                                662.0
1                                                869.0
2                                                981.0
3                                               1532.0
4                                                892.0
..                                                 ...
313                                              632.0
314                                             1142.0
315                                             1151.0
316                                             2117.0
317                                              496.0

     Economically active (excluding full-time students):In employment:Self-employed without employees  \
0                                               3676.0
1                                               5376.0
2                                               5764.0
3                                               8481.0
4                                               4881.0
..                                                 ...
313                                             3713.0
314                                             6844.0
315                                             6841.0
316                                            14229.0
317                                             2405.0

     ...  \
0    ...
1    ...
2    ...
3    ...
4    ...
..   ...
313  ...
314  ...
315  ...
316  ...
317  ...

     Economically active and a full-time student: In employment: Self-employed with employees: Full-time  \
0                                                  0.0
1                                                 11.0
2                                                  1.0
3                                                  6.0
4                                                  5.0
..                                                 ...
313                                                6.0
314                                                2.0
315                                                3.0
316                                                0.0
317                                                0.0

     Economically active and a full-time student:In employment:Self-employed without employees  \
0                                                 24.0
1                                                 99.0
2                                                 56.0
3                                                 69.0
4                                                 32.0
..                                                 ...
313                                               24.0
314                                               51.0
315                                               69.0
316                                               76.0
317                                               15.0

     Economically active and a full-time student: In employment: Self-employed without employees: Part-time  \
0                                                 16.0
1                                                 85.0
2                                                 39.0
3                                                 51.0
4                                                 22.0
..                                                 ...
313                                               19.0
314                                               40.0
315                                               51.0
316                                               52.0
317                                               11.0

     Economically active and a full-time student: In employment: Self-employed without employees: Full-time  \
0                                                  8.0
1                                                 14.0
2                                                 17.0
3                                                 18.0
4                                                 10.0
..                                                 ...
313                                                5.0
314                                               11.0
315                                               18.0
316                                               24.0
317                                                4.0

     Economically active and a full-time student: Unemployed  \
0                                                361.0
1                                               1431.0
2                                                479.0
3                                                759.0
4                                                368.0
..                                                 ...
313                                              284.0
314                                              215.0
315                                              711.0
316                                              219.0
317                                              237.0

     Economically inactive: Retired  Economically inactive: Student  \
0                           17910.0                          3463.0
1                           23267.0                          7974.0
2                           32033.0                          4444.0
3                           37038.0                          6878.0
4                           21930.0                          3229.0
..                              ...                             ...
313                         18673.0                          2811.0
314                         22877.0                          2826.0
315                         26175.0                          5732.0
316                         33173.0                          3819.0
317                         10539.0                          1973.0

     Economically inactive: Looking after home or family  \
0                                               4303.0
1                                               7527.0
2                                               5597.0
3                                               7670.0
4                                               3899.0
..                                                 ...
313                                             3455.0
314                                             2767.0
315                                             6443.0
316                                             4004.0
317                                             2263.0

     Economically inactive: Long-term sick or disabled  \
0                                               5432.0
1                                               7879.0
2                                               7268.0
3                                               8208.0
4                                               4179.0
..                                                 ...
313                                             5109.0
314                                             3058.0
315                                             7411.0
316                                             4770.0
317                                             4107.0

     Economically inactive: Other
0                          2826.0
1                          5044.0
2                          3374.0
3                          5872.0
4                          2537.0
..                            ...
313                        2123.0
314                        2152.0
315                        4362.0
316                        2718.0
317                        1611.0

[318 rows x 29 columns]>

In [21]:
df_2011.columns

Index(['local authority: district / unitary (prior to April 2015)',
       'Unnamed: 1', 'All usual residents aged 16 to 74',
       'Economically active: In employment',
       'Economically active: Employee: Part-time',
       'Economically active: Employee: Full-time',
       'Economically active: Unemployed',
       'Economically active: Full-time student',
       'Economically inactive: Retired',
       'Economically inactive: Student (including full-time students)',
       'Economically inactive: Other'],
      dtype='object')

In [40]:
df_2021_filtered.columns

Index(['Region', 'Area Code', 'Economically active: In employment',
       'Economically active: Employee: Part-time',
       'Economically active: Employee: Full-time',
       'Economically active: Unemployed',
       'Economically active: Full-time student',
       'Economically inactive: Retired',
       'Economically inactive: Student (including full-time students)',
       'Economically inactive: Other', 'Year'],
      dtype='object')

In [16]:
#econimic activity
import pandas as pd


df_2011 = pd.read_excel("excel datasets 2011 VISCOU/economic acitivity_ 2011.xlsx", skiprows=7).iloc[:-59]
df_2021 = pd.read_excel("excel datasets 2021 VISCOU/economic_activity_status_2021.xlsx", skiprows=7).iloc[:-2]

df_2011.rename(columns={df_2011.columns[0]: "Region",df_2011.columns[1]: "Area Code"}, inplace=True)
df_2021.rename(columns={df_2021.columns[0]: "Region",df_2021.columns[1]: "Area Code"}, inplace=True)

df_2011.drop("All usual residents aged 16 to 74",axis=1,inplace=True)

df_2011 = map_area_codes(df_2011)
df_2021["Economically active and a full-time student"] = (
    df_2021["Economically active and a full-time student:In employment"] +
    df_2021["Economically active and a full-time student: Unemployed"]
)


# mapping from 2021 column names to 2011 column names
column_map = {
    "Economically active (excluding full-time students):In employment": "Economically active: In employment",
    "Economically active (excluding full-time students): In employment: Employee: Part-time": "Economically active: Employee: Part-time",
    "Economically active (excluding full-time students): In employment: Employee: Full-time": "Economically active: Employee: Full-time",
    "Economically active (excluding full-time students): Unemployed": "Economically active: Unemployed",
    "Economically inactive: Retired": "Economically inactive: Retired",
    "Economically inactive: Other": "Economically inactive: Other",
      'Economically active and a full-time student:In employment': 'Economically active: Full-time student',
    'Economically inactive: Student': 'Economically inactive: Student (including full-time students)',
}

df_2021.rename(columns=column_map,inplace=True)

columns_to_keep = df_2011.columns
df_2021_filtered = df_2021[columns_to_keep].copy()


# Add year labels
df_2011["Year"] = 2011
df_2021_filtered["Year"] = 2021
df_combined = pd.concat([df_2011, df_2021_filtered], ignore_index=True)

df_combined.to_excel("economic_activity_matched_cleaned.xlsx", index=False)

print("saved:economic activity")

c:\users\satheesh\appdata\local\programs\python\python39\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\users\satheesh\appdata\local\programs\python\python39\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

saved:economic activity

In [24]:
df_2011.isna().sum()

Region                                                           0
Area Code                                                        0
Economically active: In employment                               0
Economically active: Employee: Part-time                         0
Economically active: Employee: Full-time                         0
Economically active: Unemployed                                  0
Economically active: Full-time student                           0
Economically inactive: Retired                                   0
Economically inactive: Student (including full-time students)    0
Economically inactive: Other                                     0
Year                                                             0
dtype: int64

In [25]:
df_2021_filtered

,Region,Area Code,Economically active: In employment,Economically active: Employee: Part-time,Economically active: Employee: Full-time,Economically active: Unemployed,Economically active: Full-time student,Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Other
0,Hartlepool,E06000001,36846.0,9575.0,22723.0,2641.0,903.0,17910.0,3463.0,2826.0
1,Middlesbrough,E06000002,53849.0,14198.0,33030.0,4384.0,2584.0,23267.0,7974.0,5044.0
2,Redcar and Cleveland,E06000003,54282.0,14167.0,33057.0,3525.0,1338.0,32033.0,4444.0,3374.0
3,Stockton-on-Tees,E06000004,84174.0,19945.0,53754.0,5141.0,2268.0,37038.0,6878.0,5872.0
4,Darlington,E06000005,48103.0,10748.0,31324.0,2665.0,1193.0,21930.0,3229.0,2537.0
...,...,...,...,...,...,...,...,...,...,...
313,Torfaen,W06000020,39763.0,8918.0,26357.0,2003.0,891.0,18673.0,2811.0,2123.0
314,Monmouthshire,W06000021,42025.0,9140.0,24578.0,1514.0,804.0,22877.0,2826.0,2152.0
315,Newport,W06000022,70863.0,15978.0,46516.0,3799.0,1924.0,26175.0,5732.0,4362.0
316,Powys,W06000023,60699.0,13628.0,30228.0,2107.0,1027.0,33173.0,3819.0,2718.0
317,Merthyr Tydfil,W06000024,25035.0,5761.0,16246.0,1312.0,599.0,10539.0,1973.0,1611.0

In [25]:

df = pd.read_excel("D:\\VIS coursework\\excel datasets 2011 VISCOU\\highest level of qualification_2011.xlsx",sheet_name = "Data",skiprows=7).iloc[:-60]

In [26]:
df.replace('-', pd.NA, inplace=True)
df.rename(columns={
    df.columns[0]:"Region",
    df.columns[1]:"Area Code"
},inplace=True)

In [27]:
df.isnull().sum()

Region                              0
Area Code                           0
No qualifications                   0
Level 1 qualifications              0
Level 2 qualifications              0
Apprenticeship                      1
Level 3 qualifications              0
Level 4 qualifications and above    0
Other qualifications                1
dtype: int64

In [28]:
target_cols = ['Apprenticeship', 'Other qualifications']
non_feature_cols = ['local authority: district / unitary (prior to April 2015)']
features = df.drop(columns=target_cols + non_feature_cols, errors='ignore')
features = features.apply(pd.to_numeric, errors='coerce')

In [33]:
features

,Region,Area Code,No qualifications,Level 1 qualifications,Level 2 qualifications,Level 3 qualifications,Level 4 qualifications and above
0,NaN,NaN,21179.0,11445.0,13568.0,10883.0,20244.0
1,NaN,NaN,116948.0,57032.0,67905.0,57957.0,91249.0
2,NaN,NaN,22758.0,10057.0,11992.0,9276.0,13063.0
3,NaN,NaN,33002.0,15053.0,16891.0,14542.0,20472.0
4,NaN,NaN,62584.0,35791.0,43363.0,31650.0,67024.0
...,...,...,...,...,...,...,...
344,NaN,NaN,20662.0,9035.0,8879.0,5644.0,8689.0
345,NaN,NaN,21329.0,11094.0,12052.0,8267.0,14976.0
346,NaN,NaN,15521.0,9446.0,11531.0,8107.0,24839.0
347,NaN,NaN,31454.0,16399.0,17834.0,13203.0,27202.0
348,NaN,NaN,38459.0,41913.0,28688.0,18377.0,63221.0

In [30]:

#baysien methods 
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module='openpyxl')


import pandas as pd
from sklearn.linear_model import BayesianRidge
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

imputer = SimpleImputer(strategy='mean')
features_imputed = imputer.fit_transform(features)

scaler = StandardScaler()
features_scaled = scaler.fit_transform(features_imputed)
for col in target_cols:
    target = pd.to_numeric(df[col], errors='coerce')
    not_missing = target.notna()

    model = BayesianRidge()
    model.fit(features_scaled[not_missing], target[not_missing])

    missing_mask = ~not_missing
    predicted = model.predict(features_scaled[missing_mask])
    
    df.loc[missing_mask, col] = predicted.clip(min=0)


df.to_excel("highest_level_of_qualification_2011_imputed_cleaned.xlsx", index=False)
print(" Bayesian done")
df

 Bayesian done

,Region,Area Code,No qualifications,Level 1 qualifications,Level 2 qualifications,Apprenticeship,Level 3 qualifications,Level 4 qualifications and above,Other qualifications
0,Darlington,E06000005,21179.0,11445.0,13568.0,4350,10883.0,20244.0,3688
1,County Durham,E06000047,116948.0,57032.0,67905.0,17694,57957.0,91249.0,16473
2,Hartlepool,E06000001,22758.0,10057.0,11992.0,4076,9276.0,13063.0,3006
3,Middlesbrough,E06000002,33002.0,15053.0,16891.0,4874,14542.0,20472.0,5575
4,Northumberland,E06000057,62584.0,35791.0,43363.0,11823,31650.0,67024.0,9927
...,...,...,...,...,...,...,...,...,...
344,Blaenau Gwent,W06000019,20662.0,9035.0,8879.0,2032,5644.0,8689.0,2380
345,Torfaen,W06000020,21329.0,11094.0,12052.0,3182,8267.0,14976.0,2933
346,Monmouthshire,W06000021,15521.0,9446.0,11531.0,2924,8107.0,24839.0,2712
347,Newport,W06000022,31454.0,16399.0,17834.0,4685,13203.0,27202.0,5571
348,Aberdeen City,S12000033,38459.0,41913.0,28688.0,1680.340672,18377.0,63221.0,35101.015352

In [32]:
# highest qualifiaction 
import pandas as pd

# Step 1: Load files
file_2011 = "D:\VIS coursework\highest_level_of_qualification_2011_imputed_cleaned.xlsx"
file_2021 = "D:\VIS coursework\excel datasets 2021 VISCOU\Highest level of qualification_2021.xlsx"
df_2021_raw = pd.read_excel(file_2021, skiprows=7,sheet_name="Data").iloc[:-2]
df_2011 = pd.read_excel(file_2011,sheet_name="Sheet1")

df_2011 = df_2011.rename(columns={df_2011.columns[0]: "Region",df_2011.columns[1]:"Area Code"})
df_2021_raw = df_2021_raw.rename(columns={df_2021_raw.columns[0]: "Region",df_2021.columns[1]:"Area Code"})

df_2011= map_area_codes(df_2011)

column_mapping_2021_to_2011 = {
    "No qualifications": "No qualifications",
    "Level 1 and entry level qualifications": "Level 1 qualifications",
    "Level 2 qualifications": "Level 2 qualifications",
    "Apprenticeship": "Apprenticeship",
    "Level 3 qualifications": "Level 3 qualifications",
    "Level 4 qualifications or above": "Level 4 qualifications and above",
    "Other qualifications": "Other qualifications"
}

df_2021 = df_2021_raw.rename(columns=column_mapping_2021_to_2011)

df_2011.rename(columns={df_2011.columns[1]:"Area Code", df_2011.columns[0] : "Region"}
              ,inplace=True)
df_2021.rename(columns={df_2021.columns[1]:"Area Code", df_2021.columns[0] : "Region"}
              ,inplace=True)

df_2011["Year"] = 2011
df_2021["Year"] = 2021


df_2021 = df_2021[df_2011.columns]

df_qualification = pd.concat([df_2011, df_2021], ignore_index=True)

output_file = "highest_level_of_qualification_combined_cleaned.xlsx"
df_qualification.to_excel(output_file, index=False)

print(" saved: highest qualification")

 saved: highest qualification

In [34]:
import pandas as pd
file_2011 = "D:\VIS coursework\excel datasets 2011 VISCOU\industry_of_employment_2011.xlsx"
file_2021 = "D:\VIS coursework\excel datasets 2021 VISCOU\industry_employment_2021.xlsx"


df_2011 = pd.read_excel(file_2011, skiprows=7).iloc[:-2]
df_2021 = pd.read_excel(file_2021, skiprows=7).iloc[:-2]
df_2011.columns

Index(['local authority: district / unitary (prior to April 2015)',
       'Unnamed: 1', 'A Agriculture, forestry and fishing',
       'B Mining and quarrying', 'C Manufacturing',
       'D Electricity, gas, steam and air conditioning supply',
       'E Water supply; sewerage, waste management and remediation activities',
       'F Construction',
       'G Wholesale and retail trade; repair of motor vehicles and motor cycles',
       'H Transport and storage',
       'I Accommodation and food service activities',
       'J Information and communication',
       'K Financial and insurance activities', 'L Real estate activities',
       'M Professional, scientific and technical activities',
       'N Administrative and support service activities',
       'O Public administration and defence; compulsory social security',
       'P Education', 'Q Human health and social work activities',
       'R, S, T, U Other'],
      dtype='object')

In [35]:
df_2021.columns

Index(['local authority: district / unitary (as of April 2023)', 'Unnamed: 1',
       'A: Agriculture, Forestry and fishing', 'B: Mining and quarrying',
       'C: Manufacturing',
       'D: Electricity, gas, steam and air conditioning supply',
       'E:  Water supply; Sewerage, Waste management and Remediation activities',
       'F: Construction',
       'G: Wholesale and retail trade; repair of motor vehicles and motorcycles',
       'H: Transport and storage',
       'I: Accommodation and food service activities',
       'J: Information and communication',
       'K: Financial and insurance activities', 'L: Real estate activities',
       'M: Professional, scientific and technical activities',
       'N: Administrative and support service activities',
       'O: Public administration and defence; compulsory social security',
       'P: Education', 'Q: Human health and social work activities',
       'R, S, T, U Other'],
      dtype='object')

In [36]:
df_2011.columns

Index(['local authority: district / unitary (prior to April 2015)',
       'Unnamed: 1', 'A Agriculture, forestry and fishing',
       'B Mining and quarrying', 'C Manufacturing',
       'D Electricity, gas, steam and air conditioning supply',
       'E Water supply; sewerage, waste management and remediation activities',
       'F Construction',
       'G Wholesale and retail trade; repair of motor vehicles and motor cycles',
       'H Transport and storage',
       'I Accommodation and food service activities',
       'J Information and communication',
       'K Financial and insurance activities', 'L Real estate activities',
       'M Professional, scientific and technical activities',
       'N Administrative and support service activities',
       'O Public administration and defence; compulsory social security',
       'P Education', 'Q Human health and social work activities',
       'R, S, T, U Other'],
      dtype='object')

In [37]:
import pandas as pd

file_2011_path = "D:\VIS coursework\excel datasets 2011 VISCOU\industry_of_employment_2011.xlsx"
file_2021_path = "D:\VIS coursework\excel datasets 2021 VISCOU\industry_employment_2021.xlsx"

df_2011 = pd.read_excel(file_2011_path,sheet_name="Data",skiprows=7).iloc[:-2]
df_2021 = pd.read_excel(file_2021_path,sheet_name="Data",skiprows=7).iloc[:-2]

# 'Year' column
df_2011['Year'] = 2011
df_2021['Year'] = 2021

In [38]:
df_2011.rename(columns={df_2011.columns[1]:"Area Code", df_2011.columns[0] : "Region"}
              ,inplace=True)
df_2021.rename(columns={df_2021.columns[1]:"Area Code", df_2021.columns[0] : "Region"}
              ,inplace=True)

In [39]:
set(df_2011.columns) - set(df_2021.columns)

{'A Agriculture, forestry and fishing',
 'B Mining and quarrying',
 'C Manufacturing',
 'D Electricity, gas, steam and air conditioning supply',
 'E Water supply; sewerage, waste management and remediation activities',
 'F Construction',
 'G Wholesale and retail trade; repair of motor vehicles and motor cycles',
 'H Transport and storage',
 'I Accommodation and food service activities',
 'J Information and communication',
 'K Financial and insurance activities',
 'L Real estate activities',
 'M Professional, scientific and technical activities',
 'N Administrative and support service activities',
 'O Public administration and defence; compulsory social security',
 'P Education',
 'Q Human health and social work activities'}

In [29]:
 df_2021.columns

Index(['Area Name', 'Area Code', 'A: Agriculture, Forestry and fishing',
       'B: Mining and quarrying', 'C: Manufacturing',
       'D: Electricity, gas, steam and air conditioning supply',
       'E:  Water supply; Sewerage, Waste management and Remediation activities',
       'F: Construction',
       'G: Wholesale and retail trade; repair of motor vehicles and motorcycles',
       'H: Transport and storage',
       'I: Accommodation and food service activities',
       'J: Information and communication',
       'K: Financial and insurance activities', 'L: Real estate activities',
       'M: Professional, scientific and technical activities',
       'N: Administrative and support service activities',
       'O: Public administration and defence; compulsory social security',
       'P: Education', 'Q: Human health and social work activities',
       'R, S, T, U Other', 'Year'],
      dtype='object')

In [40]:
df_2021

,Region,Area Code,"A: Agriculture, Forestry and fishing",B: Mining and quarrying,C: Manufacturing,"D: Electricity, gas, steam and air conditioning supply","E: Water supply; Sewerage, Waste management and Remediation activities",F: Construction,G: Wholesale and retail trade; repair of motor vehicles and motorcycles,H: Transport and storage,...,J: Information and communication,K: Financial and insurance activities,L: Real estate activities,"M: Professional, scientific and technical activities",N: Administrative and support service activities,O: Public administration and defence; compulsory social security,P: Education,Q: Human health and social work activities,"R, S, T, U Other",Year
0,Hartlepool,E06000001,149.0,428.0,3874.0,584.0,444.0,3809.0,5734.0,1452.0,...,834.0,628.0,544.0,1689.0,1645.0,2632.0,3763.0,6354.0,1341.0,2021
1,Middlesbrough,E06000002,82.0,604.0,3989.0,439.0,397.0,4797.0,9048.0,3102.0,...,1529.0,1203.0,762.0,2083.0,2735.0,3610.0,5282.0,11756.0,1979.0,2021
2,Redcar and Cleveland,E06000003,283.0,1052.0,4610.0,537.0,467.0,5387.0,8317.0,2676.0,...,1109.0,854.0,919.0,2557.0,2547.0,3698.0,5188.0,10322.0,2282.0,2021
3,Stockton-on-Tees,E06000004,259.0,938.0,6914.0,850.0,586.0,7319.0,13503.0,4233.0,...,2649.0,2231.0,1223.0,4629.0,3814.0,6455.0,8847.0,14889.0,3229.0,2021
4,Darlington,E06000005,311.0,135.0,4239.0,184.0,295.0,3760.0,8468.0,2869.0,...,2053.0,1455.0,522.0,2158.0,2351.0,4199.0,4293.0,7872.0,1836.0,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,Torfaen,W06000020,112.0,17.0,4705.0,298.0,444.0,3811.0,6251.0,1671.0,...,923.0,1179.0,858.0,1446.0,1614.0,4285.0,3330.0,6659.0,1488.0,2021
314,Monmouthshire,W06000021,1255.0,47.0,3374.0,240.0,351.0,3520.0,6410.0,1523.0,...,1639.0,1320.0,713.0,2897.0,1901.0,3551.0,4017.0,6289.0,1852.0,2021
315,Newport,W06000022,260.0,47.0,6144.0,539.0,735.0,4832.0,12203.0,3906.0,...,2265.0,3618.0,1060.0,3517.0,3173.0,6949.0,5835.0,11359.0,2682.0,2021
316,Powys,W06000023,5824.0,134.0,5122.0,307.0,523.0,6275.0,8600.0,2056.0,...,1347.0,788.0,595.0,2835.0,2525.0,4607.0,5193.0,9116.0,2805.0,2021
317,Merthyr Tydfil,W06000024,72.0,79.0,2849.0,177.0,415.0,2744.0,3749.0,986.0,...,751.0,443.0,344.0,643.0,1122.0,2378.0,2137.0,4870.0,807.0,2021

In [44]:
#industry employment
import pandas as pd

df_2011 = pd.read_excel("D:\VIS coursework\excel datasets 2011 VISCOU\industry_of_employment_2011.xlsx", skiprows=7).iloc[:-59]
# df_2011 = df_2011.iloc[:, :].dropna(how='all')  # Drop all-NaN rows

df_2011['Year'] = 2011

df_2021 = pd.read_excel("D:\VIS coursework\excel datasets 2021 VISCOU\industry_employment_2021.xlsx", skiprows=7).iloc[:-2]
df_2021['Year'] = 2021

In [45]:
df_2011.rename(columns={df_2011.columns[1]:"Area Code", df_2011.columns[0] : "Region"}
              ,inplace=True)
df_2021.rename(columns={df_2021.columns[1]:"Area Code", df_2021.columns[0] : "Region"}
              ,inplace=True)

In [46]:
 
df_2011= map_area_codes(df_2011)
rename_mapping = {
    "A: Agriculture, Forestry and fishing": "A Agriculture, forestry and fishing",
    "B: Mining and quarrying": "B Mining and quarrying",
    "C: Manufacturing": "C Manufacturing",
    "D: Electricity, gas, steam and air conditioning supply": "D Electricity, gas, steam and air conditioning supply",
    "E:  Water supply; Sewerage, Waste management and Remediation activities": "E Water supply; sewerage, waste management and remediation activities",
    "F: Construction": "F Construction",
    "G: Wholesale and retail trade; repair of motor vehicles and motorcycles": "G Wholesale and retail trade; repair of motor vehicles and motor cycles",
    "H: Transport and storage": "H Transport and storage",
    "I: Accommodation and food service activities": "I Accommodation and food service activities",
    "J: Information and communication": "J Information and communication",
    "K: Financial and insurance activities": "K Financial and insurance activities",
    "L: Real estate activities": "L Real estate activities",
    "M: Professional, scientific and technical activities": "M Professional, scientific and technical activities",
    "N: Administrative and support service activities": "N Administrative and support service activities",
    "O: Public administration and defence; compulsory social security": "O Public administration and defence; compulsory social security",
    "P: Education": "P Education",
    "Q: Human health and social work activities": "Q Human health and social work activities",
    "R, S, T, U Other": "R, S, T, U Other"
}
df_2021.rename(columns=rename_mapping, inplace=True)

df_2011 = df_2011[df_2021.columns]
merged_df = pd.concat([df_2011, df_2021], ignore_index=True)

merged_df.rename(columns={
    merged_df.columns[1]:"Area Code"
},inplace=True)
merged_df.to_excel("merged_cleaned_industry_employment.xlsx", index=False)

print(" saved: industry employment")

 saved: industry employment

In [47]:
merged_df

,Region,Area Code,"A Agriculture, forestry and fishing",B Mining and quarrying,C Manufacturing,"D Electricity, gas, steam and air conditioning supply","E Water supply; sewerage, waste management and remediation activities",F Construction,G Wholesale and retail trade; repair of motor vehicles and motor cycles,H Transport and storage,...,J Information and communication,K Financial and insurance activities,L Real estate activities,"M Professional, scientific and technical activities",N Administrative and support service activities,O Public administration and defence; compulsory social security,P Education,Q Human health and social work activities,"R, S, T, U Other",Year
0,Darlington,E06000005,303.0,117.0,4900.0,185.0,295.0,3743.0,8107.0,2525.0,...,2165.0,1880.0,500.0,2225.0,2086.0,3808.0,4211.0,7259.0,2007.0,2011
1,County Durham,E06000047,2124.0,922.0,29983.0,2417.0,2197.0,18824.0,33261.0,10272.0,...,4564.0,5063.0,2699.0,8789.0,9165.0,19738.0,23836.0,31923.0,9860.0,2011
2,Hartlepool,E06000001,139.0,267.0,4410.0,666.0,539.0,3764.0,5657.0,1575.0,...,645.0,789.0,588.0,1511.0,1603.0,2552.0,3641.0,5829.0,1654.0,2011
3,Middlesbrough,E06000002,82.0,387.0,4430.0,490.0,380.0,4620.0,9124.0,3002.0,...,1266.0,1358.0,702.0,2253.0,2628.0,3197.0,5362.0,9116.0,2445.0,2011
4,Northumberland,E06000057,3739.0,770.0,13569.0,858.0,1060.0,11629.0,21477.0,6210.0,...,3657.0,3480.0,2164.0,7616.0,5642.0,13421.0,13081.0,22591.0,7143.0,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,Torfaen,W06000020,112.0,17.0,4705.0,298.0,444.0,3811.0,6251.0,1671.0,...,923.0,1179.0,858.0,1446.0,1614.0,4285.0,3330.0,6659.0,1488.0,2021
663,Monmouthshire,W06000021,1255.0,47.0,3374.0,240.0,351.0,3520.0,6410.0,1523.0,...,1639.0,1320.0,713.0,2897.0,1901.0,3551.0,4017.0,6289.0,1852.0,2021
664,Newport,W06000022,260.0,47.0,6144.0,539.0,735.0,4832.0,12203.0,3906.0,...,2265.0,3618.0,1060.0,3517.0,3173.0,6949.0,5835.0,11359.0,2682.0,2021
665,Powys,W06000023,5824.0,134.0,5122.0,307.0,523.0,6275.0,8600.0,2056.0,...,1347.0,788.0,595.0,2835.0,2525.0,4607.0,5193.0,9116.0,2805.0,2021
666,Merthyr Tydfil,W06000024,72.0,79.0,2849.0,177.0,415.0,2744.0,3749.0,986.0,...,751.0,443.0,344.0,643.0,1122.0,2378.0,2137.0,4870.0,807.0,2021

In [48]:
def pivot_df(df,dim_col):
    id_vars = ['Region', 'Area Code', 'Year']
    value_vars = [col for col in df.columns if col not in id_vars]
        long_df = df.melt(id_vars=id_vars, value_vars=value_vars,
                      var_name=dim_col, value_name="Counts")
    
    return long_df


merged_df = pivot_df(merged_df,"Industry")
df_combined= pivot_df(df_combined,"Economic Activity")
df_qualification= pivot_df(df_qualification,"Qualifications")

In [49]:
merged_df.to_excel("merged_cleaned_industry_employment.xlsx", index=False)
df_combined.to_excel("merged_cleaned_economic_Activity.xlsx", index=False)
df_qualification.to_excel("merged_cleaned_highest_qualification.xlsx", index=False)
print("done")

done

In [50]:
#pca
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

df = pd.read_excel("D:\VIS coursework\cleaned_data\merged_cleaned_industry_employment.xlsx")

numeric_df = df.select_dtypes(include='number')
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_df)

pca = PCA(n_components=2)
pca_components = pca.fit_transform(scaled_data)

df['PCA1'] = pca_components[:, 0]
df['PCA2'] = pca_components[:, 1]

df.to_excel("industry_employment_with_pca.xlsx", index=False)

print(" PCA done")

 PCA done

In [51]:
#t-SNE
import pandas as pd
from sklearn.manifold import TSNE
from sklearn.preprocessing import StandardScaler

df = pd.read_excel("D:\VIS coursework\cleaned_data\highest_level_of_qualification_combined_cleaned.xlsx")  # Change filename here
numeric_df = df.select_dtypes(include='number')

scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_df)

tsne = TSNE(n_components=2, perplexity=30, n_iter=1000, random_state=42)
tsne_components = tsne.fit_transform(scaled_data)
df['TSNE1'] = tsne_components[:, 0]
df['TSNE2'] = tsne_components[:, 1]
df.to_excel("qualification_with_tsne.xlsx", index=False)

print(" t-SNE done")

 t-SNE done

In [1]:
import pandas as pd

file_paths = [
    "D:\VIS coursework\mounish_data\mounish_tabluea_data\merged_cleaned_economic_Activity.xlsx",
    "D:\VIS coursework\mounish_data\mounish_tabluea_data\merged_cleaned_highest_qualification.xlsx",
    "D:\VIS coursework\mounish_data\mounish_tabluea_data\merged_cleaned_industry_employment.xlsx",
    "D:\VIS coursework\cleaned_data\industry_employment_with_pca.xlsx",
    "D:\VIS coursework\mounish_data\mounish_tabluea_data\qualification_with_tsne.xlsx"
]

sheet_names = [
    "Economic Activity",
    "Highest Qualification",
    "industry_employment",
    "industry employment pca",
    "Highest qualification tsne"
]

dataframes = [pd.read_excel(path) for path in file_paths]
output_path = "combined_sheets.xlsx"
with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
    for df, name in zip(dataframes, sheet_names):
        df.to_excel(writer, sheet_name=name, index=False)

print("Combined Excel file saved as:", output_path)

Combined Excel file saved as: combined_sheets.xlsx